#!/bin/bash
#SBATCH --account=sk36
#SBATCH --job-name=search_csb31
#SBATCH --partition=m3h
#SBATCH --gres=gpu:P100:1
#SBATCH --time=2-00:00:00
#SBATCH --ntasks=1
#SBATCH --mem=16g
#SBATCH --cpus-per-task=4
#SBATCH --output=search_csb31.out
#SBATCH --error=search_csb31.err

module load pytorch/1.6-cuda10
nvidia-smi
python /fs04/sk36/ymah0006/hyperdarts/hyperDARTS_v3_compact_sigmoid_beta.py --name cifar10_experiment_csb31
